### ISSUE TITLE
Timestamp should be usable wherever date is.

### ISSUE THREAD

**Issue by sirherrbatka** [marijnh/Postmodern#120]
Timestamp can be converted to date, so why we can't use timestamp object in insert statement?

**Comment by sabracrolleton** [comment]
The problem is we do not know which timestamp object library will be used. For example, one user may have loaded and is using localtime. Another user may have loaded and is using simple-date.  A third user may not be using either library. If we forced localtime to be a dependency, yes, we could easily do it. I am not convinced we want to force localtime to be a dependency.

**Comment by sirherrbatka** [comment]
I see. I will just close this issue.
