### ISSUE TITLE
Invalid number of parameters thrown incorrectly.

### ISSUE THREAD

**Issue by tcmal** [marijnh/Postmodern#152]
`exec-prepared` is bugged and throws incorrect number of parameters errors when the correct number of parameters is given:

```
* (exec-prepared (dbi.driver::connection-handle *db*) 
           (slot-value (dbi::prepare *db* "SELECT * FROM USERS WHERE name = ?") 'name) 
           '("hello"))
...
  Database error: Incorrect number of parameters given for prepared statement PREPARED-STATEMENT454.
...
(CL-POSTGRES::SEND-EXECUTE #<SB-SYS:FD-STREAM for "socket 127.0.0.1:58406, peer: 127.0.0.1:5432" {10032E2413}> #<unavailable argument> #<unavailable argument> #<unavailable argument>)
   source: 'FIELD-BINARY-P
```

This error is throw from [here](https://github.com/marijnh/Postmodern/blob/db8746513728fc025ffdfbe02924fad6a338e943/cl-postgres/protocol.lisp#L457) so most likely calculation of n-parameters is off.

**Comment by PuercoPop** [comment]
The problem is you are using `?` instead of $1 inside the prepare query. I can't even prepare the prepare the query successfully, but if `dbi::prepare` would manage to do sot then it would be incorrect parameters as the query written as is takes no parameters. One thing that could be improved about the error message is to include the number of parameters expected.

This works without problems

```lisp
(cl-postgres:prepare-query (dbi.driver::connection-handle *db*) "bar" "SELECT * FROM users WHERE name=$1")

(exec-prepared (dbi.driver::connection-handle *db*) 
               "bar"
               '("hello"))
```
Trying to prepare the query as written throws an error on my side

```lisp
(cl-postgres:prepare-query (dbi.driver::connection-handle *db*) "bar" "SELECT * FROM users WHERE name=?")
```

**Comment by tcmal** [comment]
Ah, ok, thanks.
