### ISSUE TITLE
Not cleaning strings

### ISSUE THREAD

**Issue by K1D77A** [marijnh/Postmodern#320]
I am not sure if this is the desired behaviour or not but it seems that despite my columns being set as CHAR(32) when I receive from the database my strings are of type (vector character 64) and the remaining characters are all #\Nul 

I have my table:
```
      id CHAR(32) CHECK (length(id) = 32) PRIMARY KEY UNIQUE,
```

I have my query
```
--name: find-client-by-api-key @row
--Find a client by ID
SELECT id, ory_uuid, api_key, creation_time, information, processors FROM clients
WHERE (
    api_key = ?api_key
);

```
I have my class and slot type
```lisp
(defclass* has-id ()
  ((id
    :accessor id
    :initarg :id
    :type (string #.de:*default-id-length*)))
  (:export-class-name-p t)
  (:export-accessor-names-p t))
  ```
  default-id-length is 32
  
I execute:
`(core:find-client` "@0r19jbo65us4bug9zya432ozrpu2n0z")`
WIth a break on the returned ID 

I inspect the ID and it looks like:
![image](https://user-images.githubusercontent.com/10334164/235292274-201ddf0e-f3c1-43b5-846f-06711a4af24e.png)

Is this the desired behaviour? 
Do things break if nulls are stripped from strings?

Any info would be appreciated, as a workaround I will subseq it myself. I am just curious. 
Thanks

**Comment by sabracrolleton** [comment]
The short answer is that this is the expected behavior. See the function read-utf-8-string in the file Postmodern/cl-postgres/trivial-utf-8.lisp. When reading a utf-8 string, we start with a 64 element adjustable vector. The design decision was that this was the optimal length to start with. Any shorter and we incur more overhead in expanding the vector too often. 

You will notice that although you are getting a vector containing 64 characters, but when considered as a string, it only has a length of 32 (32 characters as a null terminated string with 32 nulls). You should have no problems stripping the nulls.

**Comment by K1D77A** [comment]
Thanks for the response

**Comment by phoe** [comment]
Would having strings will fill pointers on the CL side solve this better? Do we have any benchmarks to check if the performance would be still acceptable in that case?

**Comment by sabracrolleton** [comment]
I do not have any benchmarks - the design decision was made a long time ago. I am, of course, open to suggestions.

**Comment by sabracrolleton** [comment]
If someone wants to get into this, they might want to think about something configurable because some tables will have short texts and others will have longer text.
